### ISSUE TITLE
LeBlender injects Bootstrap Styles into Backoffice

### ISSUE THREAD

**Issue by WojciechKmiecik** [Lecoati/BlenderGrid#92]
LeBlender injects bootstrap template at back office, so every grid element is wrapped by the bootstrap template (with styles)

**I have the solution for that - I can create the pull request if possible - when I will get the permissions**

see the effect  : 

<img width="952" alt="effect" src="https://user-images.githubusercontent.com/9819123/38742534-22ecec7a-3f3d-11e8-99b0-21f92983a16c.png">

and when i clicked : inspect element : 

<img width="944" alt="html code" src="https://user-images.githubusercontent.com/9819123/38742931-0d706542-3f3e-11e8-88ca-09908cc97a82.png">

I dug little deeper in frontend code, so on input in the angular controller - everything looks fine
![input](https://user-images.githubusercontent.com/9819123/38742827-d39db748-3f3d-11e8-9b75-2edb781b7aa0.png)

I decompiled your code (over dotpeek / symbol server) and still, your controller returned propper values, everything was fine. Nevertheless, angular service still  returned modified object

![result from service](https://user-images.githubusercontent.com/9819123/38743089-7b1032ee-3f3e-11e8-9339-9a69eafa3c10.png)

**Comment by bjarnef** [comment]
have you tried setting `Layout = null;` as mentioned here:
https://our.umbraco.org/forum/using-umbraco-and-getting-started/84780-leblender-injects-bootstrap-styles-into-backoffice

**Comment by WojciechKmiecik** [comment]
@bjarnef - yes, I did it, in your Base.cshtml - and it worked like charm.
My point is - please document it or make that change in your code ;)

**Comment by soreng** [comment]
@WojciechKmiecik the view used to render "parts" of a page (like LeBlender does), is based on Partial-views. This is also visible in the editor. I don't feel we need to add more documentation on this, since this is the first/only I've heard of this. I think it's apparent that the render-view (the partial view) should just render the part of the page (a div or whatever) and not a full page.
