### ISSUE TITLE
Cell / Row config

### ISSUE THREAD

**Issue by hifi-phil** [Lecoati/BlenderGrid#99]
I think it would be really cool if the config for the row or the call was passed to the preview in Umbraco back office. At the moment it's just the control is passed and there's no way to adapt the preview based on any grid config settings that are set. 

I can start a pull request if anyone is interested?

**Comment by soreng** [comment]
Hi @hifi-phil 

LeBlender only handles the editors - the grid is part of umbraco :)

You should / could start an issue on http://issues.umbraco.org and then create a PR. We won't be able to push it from this repo anyways :)
